### ISSUE TITLE
Error in socket 

### ISSUE THREAD

**Issue by sajjadintel** [eusonlito/GPS-Tracker#36]
Hi, 
Server stopped working and I saw this error in the logs and didn't work till the next day.
PS. I wasn't on the latest commit 
Updating 57d26a0f..49604114

```
[2024-01-09T07:37:55+00:00] production.ERROR: ErrorException: socket_read(): unable to read from socket [104]: Connection reset by peer in /var/www/html/GPS-Tracker/app/Services/Server/Socket/Client.php:93
Stack trace:
#0 /var/www/html/GPS-Tracker/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(255): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}()
#2 /var/www/html/GPS-Tracker/app/Services/Server/Socket/Client.php(93): socket_read()
#3 /var/www/html/GPS-Tracker/app/Services/Server/Socket/Client.php(55): App\Services\Server\Socket\Client->readBuffer()
#4 /var/www/html/GPS-Tracker/app/Services/Server/Socket/Server.php(228): App\Services\Server\Socket\Client->handle()
#5 /var/www/html/GPS-Tracker/app/Services/Server/Socket/Server.php(214): App\Services\Server\Socket\Server->connectionReadHandle()
#6 /var/www/html/GPS-Tracker/app/Services/Server/Socket/Server.php(155): App\Services\Server\Socket\Server->connectionRead()
#7 /var/www/html/GPS-Tracker/app/Services/Server/Socket/Server.php(85): App\Services\Server\Socket\Server->read()
#8 /var/www/html/GPS-Tracker/app/Domains/Server/Action/StartPort.php(146): App\Services\Server\Socket\Server->accept()
#9 /var/www/html/GPS-Tracker/app/Domains/Server/Action/StartPort.php(48): App\Domains\Server\Action\StartPort->serve()
#10 /var/www/html/GPS-Tracker/app/Domains/Core/Action/ActionFactoryAbstract.php(55): App\Domains\Server\Action\StartPort->handle()
#11 /var/www/html/GPS-Tracker/app/Domains/Server/Action/ActionFactory.php(68): App\Domains\Core\Action\ActionFactoryAbstract->actionHandle()
#12 /var/www/html/GPS-Tracker/app/Domains/Server/Command/StartPort.php(29): App\Domains\Server\Action\ActionFactory->startPort()
#13 /var/www/html/GPS-Tracker/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\Domains\Server\Command\StartPort->handle()
#14 /var/www/html/GPS-Tracker/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#15 /var/www/html/GPS-Tracker/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#16 /var/www/html/GPS-Tracker/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod()
#17 /var/www/html/GPS-Tracker/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\Container\BoundMethod::call()
#18 /var/www/html/GPS-Tracker/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\Container\Container->call()
#19 /var/www/html/GPS-Tracker/vendor/symfony/console/Command/Command.php(326): Illuminate\Console\Command->execute()
#20 /var/www/html/GPS-Tracker/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Symfony\Component\Console\Command\Command->run()
#21 /var/www/html/GPS-Tracker/vendor/symfony/console/Application.php(1096): Illuminate\Console\Command->run()
#22 /var/www/html/GPS-Tracker/vendor/symfony/console/Application.php(324): Symfony\Component\Console\Application->doRunCommand()
#23 /var/www/html/GPS-Tracker/vendor/symfony/console/Application.php(175): Symfony\Component\Console\Application->doRun()
#24 /var/www/html/GPS-Tracker/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\Component\Console\Application->run()
#25 /var/www/html/GPS-Tracker/artisan(35): Illuminate\Foundation\Console\Kernel->handle()
#26 {main}  
[2024-01-09T07:37:59+00:00] production.ERROR: ErrorException: socket_read(): unable to read from socket [104]: Connection reset by peer in /var/www/html/GPS-Tracker/app/Services/Server/Socket/Client.php:93
Stack trace:
#0 /var/www/html/GPS-Tracker/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(255): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}()
#2 /var/www/html/GPS-Tracker/app/Services/Server/Socket/Client.php(93): socket_read()
#3 /var/www/html/GPS-Tracker/app/Services/Server/Socket/Client.php(55): App\Services\Server\Socket\Client->readBuffer()
#4 /var/www/html/GPS-Tracker/app/Services/Server/Socket/Server.php(228): App\Services\Server\Socket\Client->handle()
#5 /var/www/html/GPS-Tracker/app/Services/Server/Socket/Server.php(214): App\Services\Server\Socket\Server->connectionReadHandle()
#6 /var/www/html/GPS-Tracker/app/Services/Server/Socket/Server.php(155): App\Services\Server\Socket\Server->connectionRead()
#7 /var/www/html/GPS-Tracker/app/Services/Server/Socket/Server.php(85): App\Services\Server\Socket\Server->read()
#8 /var/www/html/GPS-Tracker/app/Domains/Server/Action/StartPort.php(146): App\Services\Server\Socket\Server->accept()
#9 /var/www/html/GPS-Tracker/app/Domains/Server/Action/StartPort.php(48): App\Domains\Server\Action\StartPort->serve()
#10 /var/www/html/GPS-Tracker/app/Domains/Core/Action/ActionFactoryAbstract.php(55): App\Domains\Server\Action\StartPort->handle()
#11 /var/www/html/GPS-Tracker/app/Domains/Server/Action/ActionFactory.php(68): App\Domains\Core\Action\ActionFactoryAbstract->actionHandle()
#12 /var/www/html/GPS-Tracker/app/Domains/Server/Command/StartPort.php(29): App\Domains\Server\Action\ActionFactory->startPort()
#13 /var/www/html/GPS-Tracker/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\Domains\Server\Command\StartPort->handle()
#14 /var/www/html/GPS-Tracker/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#15 /var/www/html/GPS-Tracker/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#16 /var/www/html/GPS-Tracker/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod()
#17 /var/www/html/GPS-Tracker/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\Container\BoundMethod::call()
#18 /var/www/html/GPS-Tracker/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\Container\Container->call()
#19 /var/www/html/GPS-Tracker/vendor/symfony/console/Command/Command.php(326): Illuminate\Console\Command->execute()
#20 /var/www/html/GPS-Tracker/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Symfony\Component\Console\Command\Command->run()
#21 /var/www/html/GPS-Tracker/vendor/symfony/console/Application.php(1096): Illuminate\Console\Command->run()
#22 /var/www/html/GPS-Tracker/vendor/symfony/console/Application.php(324): Symfony\Component\Console\Application->doRunCommand()
#23 /var/www/html/GPS-Tracker/vendor/symfony/console/Application.php(175): Symfony\Component\Console\Application->doRun()
#24 /var/www/html/GPS-Tracker/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\Component\Console\Application->run()
#25 /var/www/html/GPS-Tracker/artisan(35): Illuminate\Foundation\Console\Kernel->handle()
#26 {main}  

[2024-01-09T07:38:08+00:00] production.ERROR: ErrorException: socket_getpeername(): unable to retrieve peer name [107]: Transport endpoint is not connected in /var/www/html/GPS-Tracker/app/Services/Server/Connection.php:83
Stack trace:
#0 /var/www/html/GPS-Tracker/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(255): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}()
#2 /var/www/html/GPS-Tracker/app/Services/Server/Connection.php(83): socket_getpeername()
#3 /var/www/html/GPS-Tracker/app/Services/Server/Connection.php(44): App\Services\Server\Connection->setClient()
#4 /var/www/html/GPS-Tracker/app/Services/Server/Socket/Server.php(200): App\Services\Server\Connection->__construct()
#5 /var/www/html/GPS-Tracker/app/Services/Server/Socket/Server.php(181): App\Services\Server\Socket\Server->connectionAccept()
#6 /var/www/html/GPS-Tracker/app/Services/Server/Socket/Server.php(149): App\Services\Server\Socket\Server->connectionAdd()
#7 /var/www/html/GPS-Tracker/app/Services/Server/Socket/Server.php(85): App\Services\Server\Socket\Server->read()
#8 /var/www/html/GPS-Tracker/app/Domains/Server/Action/StartPort.php(146): App\Services\Server\Socket\Server->accept()
#9 /var/www/html/GPS-Tracker/app/Domains/Server/Action/StartPort.php(48): App\Domains\Server\Action\StartPort->serve()
#10 /var/www/html/GPS-Tracker/app/Domains/Core/Action/ActionFactoryAbstract.php(55): App\Domains\Server\Action\StartPort->handle()
#11 /var/www/html/GPS-Tracker/app/Domains/Server/Action/ActionFactory.php(68): App\Domains\Core\Action\ActionFactoryAbstract->actionHandle()
#12 /var/www/html/GPS-Tracker/app/Domains/Server/Command/StartPort.php(29): App\Domains\Server\Action\ActionFactory->startPort()
#13 /var/www/html/GPS-Tracker/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\Domains\Server\Command\StartPort->handle()
#14 /var/www/html/GPS-Tracker/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#15 /var/www/html/GPS-Tracker/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#16 /var/www/html/GPS-Tracker/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod()
#17 /var/www/html/GPS-Tracker/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\Container\BoundMethod::call()
#18 /var/www/html/GPS-Tracker/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\Container\Container->call()
#19 /var/www/html/GPS-Tracker/vendor/symfony/console/Command/Command.php(326): Illuminate\Console\Command->execute()
#20 /var/www/html/GPS-Tracker/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Symfony\Component\Console\Command\Command->run()
#21 /var/www/html/GPS-Tracker/vendor/symfony/console/Application.php(1096): Illuminate\Console\Command->run()
#22 /var/www/html/GPS-Tracker/vendor/symfony/console/Application.php(324): Symfony\Component\Console\Application->doRunCommand()
#23 /var/www/html/GPS-Tracker/vendor/symfony/console/Application.php(175): Symfony\Component\Console\Application->doRun()
#24 /var/www/html/GPS-Tracker/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\Component\Console\Application->run()
#25 /var/www/html/GPS-Tracker/artisan(35): Illuminate\Foundation\Console\Kernel->handle()
#26 {main}  
[2024-01-09T07:38:08+00:00] production.ERROR: socket_getpeername(): unable to retrieve peer name [107]: Transport endpoint is not connected {"url":"http://localhost","method":"GET","exception":"[object] (ErrorException(code: 0): socket_getpeername(): unable to retrieve peer name [107]: Transport endpoint is not connected at /var/www/html/GPS-Tracker/app/Services/Server/Connection.php:83)
[stacktrace]
#0 /var/www/html/GPS-Tracker/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(255): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()
#2 /var/www/html/GPS-Tracker/app/Services/Server/Connection.php(83): socket_getpeername()
#3 /var/www/html/GPS-Tracker/app/Services/Server/Connection.php(44): App\\Services\\Server\\Connection->setClient()
#4 /var/www/html/GPS-Tracker/app/Services/Server/Socket/Server.php(200): App\\Services\\Server\\Connection->__construct()
#5 /var/www/html/GPS-Tracker/app/Services/Server/Socket/Server.php(181): App\\Services\\Server\\Socket\\Server->connectionAccept()
#6 /var/www/html/GPS-Tracker/app/Services/Server/Socket/Server.php(149): App\\Services\\Server\\Socket\\Server->connectionAdd()
#7 /var/www/html/GPS-Tracker/app/Services/Server/Socket/Server.php(85): App\\Services\\Server\\Socket\\Server->read()
#8 /var/www/html/GPS-Tracker/app/Domains/Server/Action/StartPort.php(146): App\\Services\\Server\\Socket\\Server->accept()
#9 /var/www/html/GPS-Tracker/app/Domains/Server/Action/StartPort.php(48): App\\Domains\\Server\\Action\\StartPort->serve()
#10 /var/www/html/GPS-Tracker/app/Domains/Core/Action/ActionFactoryAbstract.php(55): App\\Domains\\Server\\Action\\StartPort->handle()
#11 /var/www/html/GPS-Tracker/app/Domains/Server/Action/ActionFactory.php(68): App\\Domains\\Core\\Action\\ActionFactoryAbstract->actionHandle()
#12 /var/www/html/GPS-Tracker/app/Domains/Server/Command/StartPort.php(29): App\\Domains\\Server\\Action\\ActionFactory->startPort()
#13 /var/www/html/GPS-Tracker/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Domains\\Server\\Command\\StartPort->handle()
#14 /var/www/html/GPS-Tracker/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#15 /var/www/html/GPS-Tracker/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#16 /var/www/html/GPS-Tracker/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#17 /var/www/html/GPS-Tracker/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
#18 /var/www/html/GPS-Tracker/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\\Container\\Container->call()
#19 /var/www/html/GPS-Tracker/vendor/symfony/console/Command/Command.php(326): Illuminate\\Console\\Command->execute()
#20 /var/www/html/GPS-Tracker/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Symfony\\Component\\Console\\Command\\Command->run()
#21 /var/www/html/GPS-Tracker/vendor/symfony/console/Application.php(1096): Illuminate\\Console\\Command->run()
#22 /var/www/html/GPS-Tracker/vendor/symfony/console/Application.php(324): Symfony\\Component\\Console\\Application->doRunCommand()
#23 /var/www/html/GPS-Tracker/vendor/symfony/console/Application.php(175): Symfony\\Component\\Console\\Application->doRun()
#24 /var/www/html/GPS-Tracker/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\\Component\\Console\\Application->run()
#25 /var/www/html/GPS-Tracker/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
#26 {main}
"}
```

**Comment by eusonlito** [comment]
Ok, test it now with these last commit. There are a lot of changes on socket management.

**Comment by eusonlito** [comment]
Remember to update the environment using `./composer deploy`.
