### ISSUE TITLE
Support for Cncote CE-09N

### ISSUE THREAD

**Issue by SOG-web** [eusonlito/GPS-Tracker#61]
please can I use this with Cncote devices

**Comment by eusonlito** [comment]
Could you test if it works using the GT06 protocol?

**Comment by SOG-web** [comment]
ok i will try that

**Comment by SOG-web** [comment]
do I get Real-Time Tracking for GT06 also. I have compared CE-09N protocol docs with GT06 they are both thesame

**Comment by SOG-web** [comment]
Add also I want to use my own frontend, how do I go about that. Thanks so much

**Comment by eusonlito** [comment]
Check API endpoints https://github.com/eusonlito/GPS-Tracker/wiki/%5BEN%5D-API

**Comment by SOG-web** [comment]
> do I get Real-Time Tracking for GT06 also. I have compared CE-09N protocol docs with GT06 they are both thesame

what about this @eusonlito

**Comment by eusonlito** [comment]
Yes, if are using the same protocol can you get realtime tracking.

**Comment by eusonlito** [comment]
All platform functionalities are common to all supported devices. Basically it is a real time gps tracking platform with history :)

You can check de demo to discover all features https://tracker-demo.lito.com.es/

**Comment by SOG-web** [comment]
Thanks so much so for giving time



Have been able to get it working, now I want to create device. should I put CE-09N in the model input, will it not affect the server, since am using gt06 protocol for CE-09N

**Comment by SOG-web** [comment]
And I can I configure it to support nigerian sim number for sms

**Comment by SOG-web** [comment]
Not yet solved, the server goes blank white after some minutes of running 

And also the server does not seems to be receiving any packet as per the GT06 protocol.

I don't know if am the one getting it wrong or it the server.

But I would be glad if you can jump on a Google meet call with me to help sort it out, I really need to get this done on time. 

Thanks so much

**Comment by eusonlito** [comment]
You can check if the server receives requests by making a request to the endpoint you have configured on the device like http://IP:PORT/ (always from outside the same network) and see if it is recorded in the debug log.

**Comment by SOG-web** [comment]
![17164057503406219521999650360846](https://github.com/eusonlito/GPS-Tracker/assets/61606062/8809bf93-7841-4f81-a183-dc712b2cd256)
Which one of the logs

**Comment by eusonlito** [comment]
Do you have the server started?

**Comment by SOG-web** [comment]
yes, am using docker

**Comment by eusonlito** [comment]
Check the [initial setup wiki](https://github.com/eusonlito/GPS-Tracker/wiki/%5BEN%5D-Initial-Configuration).

**Comment by SOG-web** [comment]
[2024-05-22T19:13:56+00:00] production.ERROR: App\Domains\Server\Exception\PortBusy: El servidor no se ha podido iniciar ya que el 8091 no está libre in /app/app/Domains/Server/Action/StartPort.php:137
Stack trace:
#0 /app/app/Domains/Server/Action/StartPort.php(43): App\Domains\Server\Action\StartPort->isBusyError()
#1 /app/app/Domains/Core/Action/ActionFactoryAbstract.php(55): App\Domains\Server\Action\StartPort->handle()
#2 /app/app/Domains/Server/Action/ActionFactory.php(60): App\Domains\Core\Action\ActionFactoryAbstract->actionHandle('App\\Domains\\Ser...', Array)
#3 /app/app/Domains/Server/Command/StartPort.php(29): App\Domains\Server\Action\ActionFactory->startPort()
#4 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\Domains\Server\Command\StartPort->handle()
#5 /app/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#6 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#7 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#8 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#9 /app/vendor/laravel/framework/src/Illuminate/Console/Command.php(212): Illuminate\Container\Container->call(Array)
#10 /app/vendor/symfony/console/Command/Command.php(279): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#11 /app/vendor/laravel/framework/src/Illuminate/Console/Command.php(181): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#12 /app/vendor/symfony/console/Application.php(1049): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /app/vendor/symfony/console/Application.php(318): Symfony\Component\Console\Application->doRunCommand(Object(App\Domains\Server\Command\StartPort), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /app/vendor/symfony/console/Application.php(169): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /app/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(196): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /app/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 {main}

**Comment by eusonlito** [comment]
You have configured a port (8091) but is not available. Can you change the port?

**Comment by SOG-web** [comment]
ok I will try that

**Comment by SOG-web** [comment]
have change port to 9050, the same error

**Comment by eusonlito** [comment]
Ok, let me check if there are some error with the default docker image.

**Comment by SOG-web** [comment]
the container have stop working, all port not gone invisible

**Comment by eusonlito** [comment]
Do you have some error log?

**Comment by SOG-web** [comment]
let me check

**Comment by SOG-web** [comment]
no error log, but after deleting the containers and network and rebuild, then it works again

also the port not available error only shows after start/restart the server of the port

**Comment by eusonlito** [comment]
I have upgraded the docker configuration, can you check now?

- [Upgrade Docker](https://github.com/eusonlito/GPS-Tracker/wiki/%5BEN%5D-Docker-Installation#docker-upgrade)

**Comment by SOG-web** [comment]
thanks so much, Everything seems to be working now, I will try and connect the device tomorrow morning and will give you feedback

**Comment by SOG-web** [comment]
good evening

am receiving this on the port

[2024-05-23T20:43:40+00:00] 78780d01035865710429790300000a36
[2024-05-23T20:44:58+00:00] 78780d01035865710429790300000a36
[2024-05-23T20:45:03+00:00] 78781f1218050e0f3a02c600c692ac008e9140000400026d3276700045d80001ef04
[2024-05-23T20:45:05+00:00] 78780a13050602000100020360
[2024-05-23T20:45:08+00:00] 78780a13050601000100030f25
[2024-05-23T20:45:13+00:00] 78781f12180517142d0cc600c692ac008e9140000400026d3276700045d80004a467
[2024-05-23T20:45:42+00:00] 78780d01035865710429790300000a36
[2024-05-23T20:45:49+00:00] 78781f12180517142d2fc600c692ac008e9140000400026d32767000ace700015021
[2024-05-23T20:46:01+00:00] 78780a13050601000100021eac
[2024-05-23T20:46:01+00:00] 78781f12180517142d38c600c692ac008e9140000400026d32767000ace700030a67
[2024-05-23T20:46:07+00:00] 78780a1345060200010004a150
[2024-05-23T20:46:16+00:00] 78781f12180517142e07c600c67632008ea41e001400026d32767000ace70005e9c1
[2024-05-23T20:46:27+00:00] 78781f12180517142e11c600c67632008ea41e001400026d32767000ace700062bc7
[2024-05-23T20:46:27+00:00] 78781f12180517142e1bc600c67632008ea41e001400026d32767000ace700074fc1
[2024-05-23T20:46:38+00:00] 78781f12180517142e25c600c67632008ea41e001400026d32767000ace700089986
[2024-05-23T20:46:48+00:00] 78781f12180517142e2fc600c67632008ea41e001400026d32767000ace70009fd80
[2024-05-23T20:46:57+00:00] 78781f12180517142e39c600c67632008ea41e001400026d32767000ace7000a3f86
[2024-05-23T20:47:08+00:00] 78781f12180517142f07c600c67632008ea41e001400026d32767000ace7000b5bfb
[2024-05-23T20:47:18+00:00] 78781f12180517142f11c600c67632008ea41e001400026d32767000ace7000cdfd9
[2024-05-23T20:47:28+00:00] 78781f12180517142f1bc600c67632008ea41e001400026d32767000ace7000dbbdf
[2024-05-23T20:47:37+00:00] 78781f12180517142f25c600c67632008ea41e001400026d32767000ace7000ea7f4
[2024-05-23T20:47:47+00:00] 78781f12180517142f2fc600c67632008ea41e001400026d32767000ace7000fc3f2
[2024-05-23T20:47:57+00:00] 78781f12180517142f39c600c67632008ea41e001400026d32767000ace70010db19
[2024-05-23T20:48:07+00:00] 78781f12180517143007c600c67632008ea41e001521026d32767000ace7001108b4
[2024-05-23T20:48:17+00:00] 78781f12180517143011c600c67632008ea41e001521026d32767000ace70012cab2
[2024-05-23T20:48:27+00:00] 78781f1218051714301bc600c67632008ea41e001521026d32767000ace70013aeb4
[2024-05-23T20:48:37+00:00] 78781f12180517143025c600c67632008ea41e001543026d32767000ace700147016
[2024-05-23T20:48:47+00:00] 78781f1218051714302fc600c67632008ea41e001543026d32767000ace700151410
[2024-05-23T20:48:51+00:00] 78780a134506020001001692c3
[2024-05-23T20:48:58+00:00] 78781f12180517143039c600c67632008ea41e001543026d32767000ace70017c79f
[2024-05-23T20:51:40+00:00] 78780a13450602000100187bbd
[2024-05-23T20:51:59+00:00] 78781f1218051714333ac600c67632008ea41e000543026d32767000ace7001944bf
[2024-05-23T20:52:01+00:00] 78780a130506020001001a9fa9
[2024-05-23T20:52:18+00:00] 78781f12180517143408c600c67632008ea41e000543026d32767000ace7001b98da
[2024-05-23T20:52:19+00:00] 78781f12180517143412c600c6744c008ea17b0914fc026d32767000ace7001ce901
[2024-05-23T20:52:30+00:00] 78781f1218051714341cc600c6744c008ea17b001454026d32767000ace7001d5eff
[2024-05-23T20:52:42+00:00] 78781f12180517143426c600c6744c008ea17b001403026d32767000ace7001e6974
[2024-05-23T20:52:52+00:00] 78781f12180517143430c600c6744c008ea17b001403026d32767000ace7001f8860
[2024-05-23T20:52:56+00:00] 78780a1345060200010020c676
[2024-05-23T20:52:59+00:00] 78781f1218051714343ac600c67563008ea394001403026d32767000ace700213932
[2024-05-23T20:53:09+00:00] 78781f12180517143508c600c67563008ea39400146b026d32767000ace70022b472
[2024-05-23T20:53:21+00:00] 78781f12180517143512c600c67563008ea39400152b026d32767000ace70023443c
[2024-05-23T20:53:29+00:00] 78781f1218051714351cc600c67563008ea39400152b026d32767000ace70024720a
[2024-05-23T20:53:40+00:00] 78781f12180517143526c600c67563008ea394001516026d32767000ace700255e94
[2024-05-23T20:53:49+00:00] 78781f12180517143530c600c67563008ea394001516026d32767000ace700269c92
[2024-05-23T20:53:59+00:00] 78781f1218051714353ac600c67563008ea39400155d026d32767000ace700277788
[2024-05-23T20:54:09+00:00] 78781f12180517143608c600c67563008ea3940014cd026d32767000ace700287302
[2024-05-23T20:54:19+00:00] 78781f12180517143612c600c67563008ea3940014fe026d32767000ace70029a660
[2024-05-23T20:54:29+00:00] 78781f1218051714361cc600c67563008ea3940014fe026d32767000ace7002ad672
[2024-05-23T20:54:39+00:00] 78781f12180517143626c600c67563008ea394001538026d32767000ace7002bf171
[2024-05-23T20:54:39+00:00] 78780a134506020001002c0c1a
[2024-05-23T20:54:49+00:00] 78781f12180517143630c600c67563008ea394001507026d32767000ace7002deb59
[2024-05-23T20:54:59+00:00] 78781f1218051714363ac600c67563008ea394001507026d32767000ace7002eac4d
[2024-05-23T20:55:09+00:00] 78781f12180517143708c600c67563008ea394001507026d32767000ace7002f913a
[2024-05-23T20:55:18+00:00] 78781f12180517143712c600c67563008ea394001507026d32767000ace70030d0db
[2024-05-23T20:55:28+00:00] 78781f1218051714371cc600c67563008ea394001507026d32767000ace7003183db
[2024-05-23T20:55:38+00:00] 78781f12180517143726c600c67563008ea394001507026d32767000ace70032a8f6
[2024-05-23T20:55:51+00:00] 78781f12180517143730c600c67563008ea394001507026d32767000ace7003349e2
[2024-05-23T20:57:32+00:00] 78780a134506020001003490d3
[2024-05-23T21:00:20+00:00] 78781f12180517150013c600c67563008ea394000507026d32767000ace700353bff
[2024-05-23T21:00:22+00:00] 78780a130506020001003674c7
[2024-05-23T21:00:22+00:00] 78780a1305060200010037654e
[2024-05-23T21:00:30+00:00] 78781f1218051715001dc600c67563008ea394000507026d32767000ace70038a293
[2024-05-23T21:00:40+00:00] 78781f12180517150027c600c673fb008ea301001507026d32767000ace700399464
[2024-05-23T21:00:50+00:00] 78781f12180517150031c600c673fb008ea301001507026d32767000ace7003a5662
[2024-05-23T21:01:00+00:00] 78781f1218051715003bc600c673fb008ea301001507026d32767000ace7003b3264
[2024-05-23T21:01:10+00:00] 78781f12180517150109c600c673fb008ea301001454026d32767000ace7003cad83
[2024-05-23T21:01:20+00:00] 78781f12180517150113c600c673fb008ea30100144e026d32767000ace7003d7350
[2024-05-23T21:01:30+00:00] 78781f1218051715011dc600c673fb008ea301001468026d32767000ace7003e14bf
[2024-05-23T21:01:40+00:00] 78781f12180517150127c600c673fb008ea30100144f026d32767000ace7003f5eec
[2024-05-23T21:01:50+00:00] 78781f12180517150131c600c673fb008ea30100144f026d32767000ace700402501
[2024-05-23T21:02:00+00:00] 78781f1218051715013bc600c673fb008ea30100144f026d32767000ace700414107
[2024-05-23T21:02:10+00:00] 78781f12180517150209c600c673fb008ea30100144f026d32767000ace70042e9ea
[2024-05-23T21:02:20+00:00] 78781f12180517150213c600c673fb008ea30100144f026d32767000ace7004351f4
[2024-05-23T21:02:29+00:00] 78781f1218051715021dc600c673fb008ea3010014f2026d32767000ace70044d178
[2024-05-23T21:02:39+00:00] 78781f12180517150227c600c673fb008ea301001517026d32767000ace70045ea42
[2024-05-23T21:02:49+00:00] 78781f12180517150231c600c673fb008ea301001517026d32767000ace700462844
[2024-05-23T21:02:59+00:00] 78781f1218051715023bc600c673fb008ea301001517026d32767000ace700474c42
[2024-05-23T21:03:09+00:00] 78781f12180517150309c600c673fb008ea30100150d026d32767000ace70048fe86
[2024-05-23T21:03:21+00:00] 78780a134506020001004938b1
[2024-05-23T21:05:44+00:00] 78781f1218051715052bc600c673fb008ea301000448026d32767000ace7004af3f3
[2024-05-23T21:05:46+00:00] 78780a130506020001004bdca5
[2024-05-23T21:05:54+00:00] 78781f12180517150535c600c673fb008ea301000448026d32767000ace7004c0854
[2024-05-23T21:06:04+00:00] 78781f12180517150603c600c67572008ea35b001448026d32767000ace7004dde58
[2024-05-23T21:06:13+00:00] 78780a134506020001004e4c0e
[2024-05-23T21:06:15+00:00] 78781f1218051715060dc600c67572008ea35b001448026d32767000ace7004fbfc3
[2024-05-23T21:06:24+00:00] 78781f12180517150617c600c67572008ea35b001448026d32767000ace70050fe22
[2024-05-23T21:06:34+00:00] 78781f12180517150621c600c67572008ea35b001448026d32767000ace70051af17
[2024-05-23T21:06:44+00:00] 78781f1218051715062bc600c67572008ea35b001448026d32767000ace70052e803
[2024-05-23T21:06:53+00:00] 78781f12180517150635c600c67572008ea35b001448026d32767000ace70053671b
[2024-05-23T21:07:03+00:00] 78781f12180517150703c600c67572008ea35b001448026d32767000ace70054085c
[2024-05-23T21:07:13+00:00] 78781f1218051715070dc600c67572008ea35b001448026d32767000ace700555b5c
[2024-05-23T21:07:23+00:00] 78781f12180517150717c600c67572008ea35b001438026d32767000ace700569e9a
[2024-05-23T21:07:33+00:00] 78781f12180517150721c600c674fa008ea36d001438026d32767000ace7005752a3
[2024-05-23T21:07:43+00:00] 78781f1218051715072bc600c674fa008ea36d001526026d32767000ace700586216
[2024-05-23T21:07:53+00:00] 78781f12180517150735c600c67545008ea2d1001526026d32767000ace700594556
[2024-05-23T21:08:03+00:00] 78781f12180517150803c600c67530008ea35e00154a026d32767000ace7005a3b19
[2024-05-23T21:08:13+00:00] 78781f1218051715080dc600c67524008ea38b001487026d32767000ace7005b9629
[2024-05-23T21:08:23+00:00] 78781f12180517150817c600c67524008ea38b001487026d32767000ace7005c4b01
[2024-05-23T21:08:33+00:00] 78781f12180517150821c600c67524008ea38b001487026d32767000ace7005d1a34
[2024-05-23T21:08:43+00:00] 78781f1218051715082bc600c67524008ea38b001471026d32767000ace7005e6486
[2024-05-23T21:08:53+00:00] 78781f12180517150835c600c67524008ea38b001402026d32767000ace7005f4be7
[2024-05-23T21:09:03+00:00] 78781f12180517150903c600c67524008ea38b001402026d32767000ace70060996b
[2024-05-23T21:09:12+00:00] 78780a134506020001006195fb
[2024-05-23T21:09:13+00:00] 78781f1218051715090dc600c67524008ea38b001402026d32767000ace70062f8f0
[2024-05-23T21:09:23+00:00] 78781f12180517150917c600c67524008ea38b001525026d32767000ace7006387d7
[2024-05-23T21:09:33+00:00] 78781f12180517150921c600c67524008ea38b001525026d32767000ace70064b3d4
[2024-05-23T21:09:42+00:00] 78780a1345060200010065d3df
[2024-05-23T21:09:43+00:00] 78781f1218051715092bc600c67500008ea3b5001525026d32767000ace70066698f
[2024-05-23T21:09:55+00:00] 78781f12180517150935c600c67500008ea3b5001545026d32767000ace70067c918
[2024-05-23T21:10:03+00:00] 78781f12180517150a03c600c67500008ea3b5001545026d32767000ace700689c9f
[2024-05-23T21:10:14+00:00] 78781f12180517150a0dc600c67500008ea3b5001545026d32767000ace70069cf9f
[2024-05-23T21:10:23+00:00] 78781f12180517150a16c600c67500008ea3b5001538026d32767000ace7006a34fe
[2024-05-23T21:10:33+00:00] 78781f12180517150a20c600c67500008ea3b500149b026d32767000ace7006b6ebc
[2024-05-23T21:10:43+00:00] 78781f12180517150a2ac600c67500008ea3b50014af026d32767000ace7006ca216
[2024-05-23T21:10:53+00:00] 78781f12180517150a34c600c67500008ea3b50014ad026d32767000ace7006d862c
[2024-05-23T21:11:03+00:00] 78781f12180517150b02c600c67500008ea3b500152b026d32767000ace7006e4d76
[2024-05-23T21:11:13+00:00] 78781f12180517150b0cc600c67500008ea3b500154a026d32767000ace7006f6468
[2024-05-23T21:11:23+00:00] 78781f12180517150b16c600c67500008ea3b50014f3026d32767000ace700704833
[2024-05-23T21:11:33+00:00] 78781f12180517150b20c600c67500008ea3b5001543026d32767000ace700719d87
[2024-05-23T21:11:43+00:00] 78781f12180517150b2ac600c67500008ea3b5001429026d32767000ace7007267c1
[2024-05-23T21:11:53+00:00] 78781f12180517150b34c600c67500008ea3b50014ea026d32767000ace700734974
[2024-05-23T21:12:03+00:00] 78781f12180517150c02c600c67500008ea3b50014ea026d32767000ace70074f5ba
[2024-05-23T21:12:27+00:00] 78780a1345060200010075c35e
[2024-05-23T21:12:27+00:00] 78781f12180517150c0cc600c67500008ea3b500151f026d32767000ace70076d661
[2024-05-23T21:12:27+00:00] 78781f12180517150c16c600c67500008ea3b500151f026d32767000ace700776e7f
[2024-05-23T21:12:34+00:00] 78781f12180517150c20c600c67500008ea3b5081472026d32767000ace70078e6e8
[2024-05-23T21:13:32+00:00] 78781f12180517150d1fc600c67500008ea3b5000472026d32767000ace7007933ec
[2024-05-23T21:13:52+00:00] 78781f12180517150d29c600c67500008ea3b5000472026d32767000ace7007a41cb
[2024-05-23T21:13:52+00:00] 78781f12180517150d33c600c6759c008ea36a001450026d32767000ace7007b5747
[2024-05-23T21:14:02+00:00] 78781f12180517150e01c600c6759f008ea424001449026d32767000ace7007d63e7
[2024-05-23T21:14:15+00:00] 78781f12180517150e0bc600c6754e008ea2e9001449026d32767000ace7007e7bf7
[2024-05-23T21:16:08+00:00] 78781f12180517150e15c600c6754e008ea2e9071437026d32767000ace7007ffbbb
[2024-05-23T21:16:08+00:00] 78781f12180517150e1fc600c6754e008ea2e900143e026d32767000ace700807034
[2024-05-23T21:16:08+00:00] 78781f12180517150e29c600c6754e008ea2e90014f5026d32767000ace700813c06
[2024-05-23T21:16:08+00:00] 78781f12180517150e33c600c6754e008ea2e90014f5026d32767000ace70082a70a
[2024-05-23T21:16:08+00:00] 78781f12180517150f01c600c6754e008ea2e90014f5026d32767000ace700839a7d
[2024-05-23T21:16:08+00:00] 78780a13450602000100842558
[2024-05-23T21:16:08+00:00] 78781f12180517150f0bc600c6754e008ea2e90014f5026d3276700045d800850b44
[2024-05-23T21:16:08+00:00] 78781f12180517150f15c600c6754e008ea2e90014f5026d32767000ace7008626ce
[2024-05-23T21:16:08+00:00] 78781f12180517150f1fc600c6754e008ea2e9001432026d32767000ace70087bd30
[2024-05-23T21:16:08+00:00] 78781f12180517150f29c600c6754e008ea2e9001432026d32767000ace70088057b
[2024-05-23T21:16:08+00:00] 78781f12180517150f33c600c6754e008ea2e90714eb026d32767000ace700896246
[2024-05-23T21:16:08+00:00] 78781f12180517151001c600c6754e008ea2e90014f3026d32767000ace7008a2c11
<div class="open_grepper_editor" title="Edit &amp; Save To Grepper"></div>

**Comment by eusonlito** [comment]
Great!

**Comment by SOG-web** [comment]
Thanks, so much
