### ISSUE TITLE
Error when try to open log from server page

### ISSUE THREAD

**Issue by chitkiu** [eusonlito/GPS-Tracker#84]
When I try to open server log from Server -> Status -> Log I have 500 error. If I open Monitor -> Logs - all good.
Error log:

```
[2024-10-31T08:38:36+00:00] production.ERROR: DirectoryIterator::__construct(/var/www/tracker/storage/logs/server/2024/10/31/8091.log): Failed to open directory: Not a directory {"userId":1,"url":"https://*here url*/monitor/log/c2VydmVyLzIwMjQvMTAvMzEvODA5MS5sb2c=","method":"GET","exception":"[object] (UnexpectedValueException(code: 0): DirectoryIterator::__construct(/var/www/tracker/storage/logs/server/2024/10/31/8091.log): Failed to open directory: Not a directory at /var/www/tracker/app/Domains/Monitor/Service/Controller/Log.php:53)
[stacktrace]
#0 /var/www/tracker/app/Domains/Monitor/Service/Controller/Log.php(53): DirectoryIterator->__construct()
#1 /var/www/tracker/app/Domains/Monitor/Service/Controller/Log.php(34): App\\Domains\\Monitor\\Service\\Controller\\Log->list()
#2 /var/www/tracker/app/Domains/Monitor/Controller/Log.php(29): App\\Domains\\Monitor\\Service\\Controller\\Log->data()
#3 /var/www/tracker/app/Domains/Monitor/Controller/Log.php(19): App\\Domains\\Monitor\\Controller\\Log->data()
#4 /var/www/tracker/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Domains\\Monitor\\Controller\\Log->__invoke()
#5 /var/www/tracker/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\\Routing\\Controller->callAction()
#6 /var/www/tracker/vendor/laravel/framework/src/Illuminate/Routing/Route.php(264): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#7 /var/www/tracker/vendor/laravel/framework/src/Illuminate/Routing/Route.php(210): Illuminate\\Routing\\Route->runController()
#8 /var/www/tracker/vendor/laravel/framework/src/Illuminate/Routing/Router.php(808): Illuminate\\Routing\\Route->run()
#9 /var/www/tracker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#10 /var/www/tracker/app/Domains/Core/Controller/ControllerAbstract.php(40): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#11 /var/www/tracker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(165): App\\Domains\\Core\\Controller\\ControllerAbstract->setup()
#12 /var/www/tracker/app/Domains/User/Middleware/Admin.php(24): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#13 /var/www/tracker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\\Domains\\User\\Middleware\\Admin->handle()
#14 /var/www/tracker/app/Domains/User/Middleware/Enabled.php(24): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#15 /var/www/tracker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\\Domains\\User\\Middleware\\Enabled->handle()
#16 /var/www/tracker/app/Domains/User/Middleware/Request.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#17 /var/www/tracker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\\Domains\\User\\Middleware\\Request->handle()
#18 /var/www/tracker/app/Domains/IpLock/Middleware/Check.php(20): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#19 /var/www/tracker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\\Domains\\IpLock\\Middleware\\Check->handle()
#20 /var/www/tracker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#21 /var/www/tracker/vendor/laravel/framework/src/Illuminate/Routing/Router.php(807): Illuminate\\Pipeline\\Pipeline->then()
#22 /var/www/tracker/vendor/laravel/framework/src/Illuminate/Routing/Router.php(786): Illuminate\\Routing\\Router->runRouteWithinStack()
#23 /var/www/tracker/vendor/laravel/framework/src/Illuminate/Routing/Router.php(750): Illuminate\\Routing\\Router->runRoute()
#24 /var/www/tracker/vendor/laravel/framework/src/Illuminate/Routing/Router.php(739): Illuminate\\Routing\\Router->dispatchToRoute()
#25 /var/www/tracker/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(201): Illuminate\\Routing\\Router->dispatch()
#26 /var/www/tracker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#27 /var/www/tracker/app/Domains/Language/Middleware/Request.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#28 /var/www/tracker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\\Domains\\Language\\Middleware\\Request->handle()
#29 /var/www/tracker/app/Http/Middleware/MessagesShareFromSession.php(23): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#30 /var/www/tracker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\\Http\\Middleware\\MessagesShareFromSession->handle()
#31 /var/www/tracker/app/Http/Middleware/Reset.php(22): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#32 /var/www/tracker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\\Http\\Middleware\\Reset->handle()
#33 /var/www/tracker/app/Http/Middleware/RequestLogger.php(20): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#34 /var/www/tracker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\\Http\\Middleware\\RequestLogger->handle()
#35 /var/www/tracker/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#36 /var/www/tracker/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(51): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#37 /var/www/tracker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#38 /var/www/tracker/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#39 /var/www/tracker/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#40 /var/www/tracker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Session\\Middleware\\StartSession->handle()
#41 /var/www/tracker/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#42 /var/www/tracker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#43 /var/www/tracker/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(75): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 /var/www/tracker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#45 /var/www/tracker/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(110): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#46 /var/www/tracker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#47 /var/www/tracker/app/Http/Middleware/Https.php(23): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 /var/www/tracker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\\Http\\Middleware\\Https->handle()
#49 /var/www/tracker/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(58): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#50 /var/www/tracker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#51 /var/www/tracker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#52 /var/www/tracker/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Pipeline\\Pipeline->then()
#53 /var/www/tracker/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#54 /var/www/tracker/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle()
#55 {main}
"} 

```

**Comment by eusonlito** [comment]
Good catch! Solved!

Update your environment with `./composer deploy`.
